global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: cadvisor
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: lab-backend
    static_configs:
      - targets: ['lab-backend:8080']

  - job_name: frontend-app
    metrics_path: /api/metrics
    static_configs:
      - targets: ['lab-frontend-app:3000']

  - job_name: 'blockchain-node-health'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://host.docker.internal:9944/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9115
